spring:
  config:
    import: optional:.env[.properties]
  liquibase:
    enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: news-service
server:
  port: 8086
jwt:
  secret: ${JWT_SECRET}
file-storage:
  local:
    service:
      path: ${LOCAL_STORAGE_PATH}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(%logger{36}){cyan} - %clr(%msg%n){faint}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/news-service.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: logs/news-service-%d{yyyy-MM-dd}.%i.log
  level:
    by.kotik: info