spring:
  config:
    import: optional:.env[.properties]
  liquibase:
    enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: news-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: comment-created-or-deleted
      properties:
        spring:
          json:
            trusted:
              packages: event
      auto-offset-reset: earliest
server:
  port: 8086
kafka:
  topic:
    news-deleted-topic-name: news-deleted
    comment-created-or-deleted-topic-name: comment-created-or-deleted
jwt:
  secret: ${JWT_SECRET}
file-storage:
  local:
    service:
      preview-image-folder-name: ${LOCAL_STORAGE_PREVIEW_IMAGE_FOLDER_NAME}
      path: ${LOCAL_STORAGE_PATH}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(%logger{36}){cyan} - %clr(%msg%n){faint}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/news-service.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: logs/news-service-%d{yyyy-MM-dd}.%i.log
  level:
    by.kotik: info