server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
jwt:
  secret: ${JWT_SECRET}
frontend:
  url: ${FRONTEND_URL}
spring:
  config:
    import: optional:.env[.properties]
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**, /resources/**
            - id: mail-service
              uri: lb://mail-service
              predicates:
                - Path=/mail/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: news-service
              uri: lb://news-service
              predicates:
                - Path=/news/**
            - id: comment-service
              uri: lb://comment-service
              predicates:
                - Path=/comments/**

