spring:
  config:
    import: optional:.env[.properties]
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  liquibase:
    enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8084
jwt:
  secret: ${JWT_SECRET}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(%logger{36}){cyan} - %clr(%msg%n){faint}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mail-service.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: logs/mail-service-%d{yyyy-MM-dd}.%i.log
  level:
    by.kotik: info
frontend:
  url: ${FRONTEND_URL}