spring:
  config:
    import: optional:.env[.properties]
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  liquibase:
    enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
